Facebook does not support PHP anymore:
https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html
https://travis-ci.org/awesomite/var-dumper/jobs/498810607

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'array_pop() expects parameter 1 by reference, but the call was not annotated with '&'' in phar://composer.phar/bin/../src/../src/Composer/Util/Silencer.php:51